In [1]:
import pandas as pd
pd.options.display.max_columns=1000

In [2]:
element_list = [
    'Ag', 'Al', 'As', 'Au', 'B', 'Ba', 'Be', 'Bi', 'Br', 'C', 'Ca', 'Cd', 'Ce', 'Cl', 
    'Co', 'Cr', 'Cs', 'Cu', 'Dy', 'Er', 'Eu', 'F', 'Fe', 'Ga', 'Gd', 'Ge', 'H', 'Hf', 'Hg', 
    'Ho', 'I', 'In', 'Ir', 'K', 'La', 'Li', 'Lu', 'Mg', 'Mn', 'Mo', 'N', 'Na', 'Nb', 
    'Nd', 'Ni', 'Np', 'O', 'Os', 'P', 'Pa', 'Pb', 'Pd', 'Pm', 'Pr', 'Pt', 'Pu', 'Rb', 
    'Re', 'Rh', 'Ru', 'S', 'Sb', 'Sc', 'Se', 'Si', 'Sm', 'Sn', 'Sr', 'Ta', 'Tb', 'Tc', 
    'Te', 'Th', 'Ti', 'Tl', 'Tm', 'U', 'V', 'W', 'Y', 'Yb', 'Zn', 'Zr'
]

In [3]:
elements = pd.DataFrame(element_list,columns=["Name"])

In [4]:
from pymatgen.core.periodic_table import Element
from matminer.featurizers.composition import ElementProperty

for i in range(len(elements)):
    ele = Element(elements.loc[i, "Name"])
    ele_prop = ElementProperty.from_preset('magpie')
    
    elements.loc[i, 'Z'] = ele.Z
    elements.loc[i, 'M'] = ele.atomic_mass
    elements.loc[i, 'G'] = ele.group
    elements.loc[i, 'IEI'] = ele_prop.data_source.get_elemental_property(ele, 'FirstIonizationEnergy')
    elements.loc[i, 'IEII'] = ele_prop.data_source.get_elemental_property(ele, 'SecondIonizationEnergy')
    elements.loc[i, 'EA'] = ele_prop.data_source.get_elemental_property(ele, 'ElectronAffinity')
    elements.loc[i, 'ChiP'] = ele.X
    elements.loc[i, 'ChiA'] = ele_prop.data_source.get_elemental_property(ele, 'AllenElectronegativity')
    elements.loc[i, 'Rvdw'] = ele.van_der_waals_radius
    elements.loc[i, 'Rc'] = ele_prop.data_source.get_elemental_property(ele, 'CovalentRadius')
    elements.loc[i, 'Ra'] = ele.atomic_radius
    elements.loc[i, 'Rpp_s'] = ele_prop.data_source.get_elemental_property(ele, 'ZungerPP-r_s')
    elements.loc[i, 'Rpp_p'] = ele_prop.data_source.get_elemental_property(ele, 'ZungerPP-r_p')
    elements.loc[i, 'Rpp_d'] = ele_prop.data_source.get_elemental_property(ele, 'ZungerPP-r_d')
    elements.loc[i, 'MP'] = ele.melting_point
    elements.loc[i, 'BP'] = ele.boiling_point
    elements.loc[i, 'Rho'] = ele.density_of_solid
    elements.loc[i, 'MV'] = ele.molar_volume
    elements.loc[i, 'Hf'] = ele_prop.data_source.get_elemental_property(ele, 'HeatFusion')
    elements.loc[i, 'Hv'] = ele_prop.data_source.get_elemental_property(ele, 'HeatVaporization')
    elements.loc[i, 'Kappa'] = ele.thermal_conductivity
    elements.loc[i, 'CvM'] = ele_prop.data_source.get_elemental_property(ele, 'HeatCapacityMass')
    
    elements.loc[i, 'B'] = ele.block
    elements.loc[i, 'MendeleevNo'] = ele.mendeleev_no
    elements.loc[i, 'PoissonsRatio'] = ele.poissons_ratio
    elements.loc[i, 'Kbulk'] = ele.bulk_modulus
    elements.loc[i, 'YoungsModulus'] = ele.youngs_modulus
    elements.loc[i, 'CoefficientOfLinearThermalExpansion'] = ele.coefficient_of_linear_thermal_expansion
    elements.loc[i, 'AverageCationicRadius'] = ele.average_cationic_radius
    elements.loc[i, 'AverageAnionicRadius'] = ele.average_anionic_radius

In [5]:
elements.describe()

,Z,M,G,IEI,IEII,EA,ChiP,ChiA,Rvdw,Rc,Ra,Rpp_s,Rpp_p,Rpp_d,MP,BP,Rho,MV,Hf,Hv,Kappa,CvM,MendeleevNo,PoissonsRatio,Kbulk,YoungsModulus,CoefficientOfLinearThermalExpansion,AverageCationicRadius,AverageAnionicRadius
count,83.000000,83.000000,83.000000,83.000000,76.000000,78.000000,83.000000,69.000000,83.000000,83.000000,83.000000,63.000000,63.000000,48.000000,83.000000,82.000000,76.000000,83.000000,82.000000,83.000000,83.000000,78.000000,83.000000,54.000000,69.000000,63.000000,63.000000,83.000000,83.000000
mean,46.096386,110.787887,7.710843,7.628969,18.189480,78.160897,1.745783,1.751087,2.131928,152.506024,1.489157,0.981825,1.188841,0.406729,1378.710843,2721.806463,8444.552632,16.395663,16.100683,291.785807,65.095175,0.598885,57.084337,0.292444,90.794203,110.492063,0.000016,0.887341,0.179880
std,25.987621,67.636664,5.327174,2.409495,9.338562,78.009563,0.633088,0.659252,0.321902,40.891997,0.393782,0.326511,0.510626,0.184382,913.429383,1525.055274,5697.305830,10.460144,17.392826,204.767621,83.228356,1.642770,28.355842,0.072547,95.957835,120.801584,0.000018,0.320009,0.529218
min,1.000000,1.007940,1.000000,3.893905,10.003830,0.000000,0.790000,0.659000,1.100000,31.000000,0.250000,0.250000,0.155000,0.143000,14.010000,20.280000,535.000000,4.390000,0.060000,0.452000,0.008900,0.116000,8.000000,0.032000,1.100000,1.700000,0.000003,0.000000,0.000000
25%,24.500000,53.467073,3.000000,6.010400,12.154500,29.950000,1.235000,1.380000,1.975000,130.000000,1.350000,0.765000,0.860000,0.257500,585.610000,1505.500000,4741.000000,9.735000,6.202500,132.500000,13.000000,0.175250,29.500000,0.252500,28.000000,37.000000,0.000007,0.743333,0.000000
50%,46.000000,106.420000,6.000000,7.280000,16.415770,50.000000,1.650000,1.680000,2.130000,146.000000,1.450000,0.990000,1.230000,0.392500,1297.000000,2968.500000,7310.000000,14.020000,11.203000,290.000000,35.000000,0.243500,60.000000,0.280000,45.000000,68.000000,0.000011,0.880000,0.000000
75%,67.500000,166.094660,13.000000,8.523310,19.877125,105.375000,2.170000,2.010000,2.305000,190.000000,1.750000,1.215000,1.495000,0.514000,1834.525000,3664.500000,10702.500000,19.790000,19.872500,407.500000,89.500000,0.479000,80.500000,0.337500,140.000000,129.000000,0.000020,1.080000,0.000000
max,94.000000,244.000000,17.000000,17.422800,75.640000,349.000000,3.980000,4.193000,3.430000,244.000000,2.600000,1.710000,2.600000,0.940000,3800.000000,5869.000000,22650.000000,70.940000,117.400000,800.000000,430.000000,14.304000,103.000000,0.450000,380.000000,528.000000,0.000120,1.810000,2.070000

In [6]:
elements.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 31 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Name                                 83 non-null     object
 1   Z                                    83 non-null     float64
 2   M                                    83 non-null     float64
 3   G                                    83 non-null     float64
 4   IEI                                  83 non-null     float64
 5   IEII                                 76 non-null     float64
 6   EA                                   78 non-null     float64
 7   ChiP                                 83 non-null     float64
 8   ChiA                                 69 non-null     float64
 9   Rvdw                                 83 non-null     float64
 10  Rc                                   83 non-null     float64
 11  Ra                                   83 non-null     float64
 12  Rpp_s                                63 non-null     float64
 13  Rpp_p                                63 non-null     float64
 14  Rpp_d                                48 non-null     float64
 15  MP                                   83 non-null     float64
 16  BP                                   82 non-null     float64
 17  Rho                                  76 non-null     float64
 18  MV                                   83 non-null     float64
 19  Hf                                   82 non-null     float64
 20  Hv                                   83 non-null     float64
 21  Kappa                                83 non-null     float64
 22  CvM                                  78 non-null     float64
 23  B                                    83 non-null     object
 24  MendeleevNo                          83 non-null     float64
 25  PoissonsRatio                        54 non-null     float64
 26  Kbulk                                69 non-null     float64
 27  YoungsModulus                        63 non-null     float64
 28  CoefficientOfLinearThermalExpansion  63 non-null     float64
 29  AverageCationicRadius                83 non-null     float64
 30  AverageAnionicRadius                 83 non-null     float64
dtypes: float64(29), object(2)
memory usage: 20.2+ KB

In [7]:
elements.to_csv('elements.csv')

In [8]:
from mendeleev.fetch import fetch_table
import pandas as pd

# Fetch the periodic table data
ptable = fetch_table('elements')

In [9]:
ptable.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 69 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   annotation                     118 non-null    object
 1   atomic_number                  118 non-null    int64
 2   atomic_radius                  90 non-null     float64
 3   atomic_volume                  91 non-null     float64
 4   block                          118 non-null    object
 5   density                        118 non-null    float64
 6   description                    109 non-null    object
 7   dipole_polarizability          117 non-null    float64
 8   electron_affinity              77 non-null     float64
 9   electronic_configuration       118 non-null    object
 10  evaporation_heat               88 non-null     float64
 11  fusion_heat                    75 non-null     float64
 12  group_id                       90 non-null     float64
 13  lattice_constant               87 non-null     float64
 14  lattice_structure              91 non-null     object
 15  name                           118 non-null    object
 16  period                         118 non-null    int64
 17  series_id                      118 non-null    int64
 18  specific_heat_capacity         85 non-null     float64
 19  symbol                         118 non-null    object
 20  thermal_conductivity           66 non-null     float64
 21  vdw_radius                     103 non-null    float64
 22  covalent_radius_cordero        96 non-null     float64
 23  covalent_radius_pyykko         118 non-null    float64
 24  en_pauling                     85 non-null     float64
 25  en_allen                       71 non-null     float64
 26  jmol_color                     109 non-null    object
 27  cpk_color                      103 non-null    object
 28  proton_affinity                32 non-null     float64
 29  gas_basicity                   32 non-null     float64
 30  heat_of_formation              89 non-null     float64
 31  c6                             43 non-null     float64
 32  covalent_radius_bragg          37 non-null     float64
 33  vdw_radius_bondi               28 non-null     float64
 34  vdw_radius_truhlar             16 non-null     float64
 35  vdw_radius_rt                  9 non-null      float64
 36  vdw_radius_batsanov            65 non-null     float64
 37  vdw_radius_dreiding            21 non-null     float64
 38  vdw_radius_uff                 103 non-null    float64
 39  vdw_radius_mm3                 94 non-null     float64
 40  abundance_crust                88 non-null     float64
 41  abundance_sea                  81 non-null     float64
 42  molcas_gv_color                103 non-null    object
 43  en_ghosh                       103 non-null    float64
 44  vdw_radius_alvarez             94 non-null     float64
 45  c6_gb                          86 non-null     float64
 46  atomic_weight                  118 non-null    float64
 47  atomic_weight_uncertainty      74 non-null     float64
 48  is_monoisotopic                21 non-null     object
 49  is_radioactive                 118 non-null    bool
 50  cas                            118 non-null    object
 51  atomic_radius_rahm             96 non-null     float64
 52  geochemical_class              76 non-null     object
 53  goldschmidt_class              118 non-null    object
 54  metallic_radius                56 non-null     float64
 55  metallic_radius_c12            63 non-null     float64
 56  covalent_radius_pyykko_double  108 non-null    float64
 57  covalent_radius_pyykko_triple  80 non-null     float64
 58  discoverers                    118 non-null    object
 59  discovery_year                 105 non-null    float64
 60  discovery_location             105 non-null    object
 61  name_origin                    118 non-null    object
 62  sources                        118 non-null    object
 63  uses                           112 non-null    object
 64  mendeleev_number               118 non-null    int64
 65  dipole_polarizability_unc      117 non-null    float64
 66  pettifor_number                103 non-null    float64
 67  glawe_number                   103 non-null    float64
 68  molar_heat_capacity            85 non-null     float64
dtypes: bool(1), float64(45), int64(4), object(19)
memory usage: 62.9+ KB

In [10]:
# List of properties to include in the dataframe
cols = ['symbol', 'atomic_number', 'atomic_weight', 'group_id', 'period', 'electron_affinity', 'en_pauling',
        'en_allen', 'vdw_radius', 'covalent_radius_pyykko', 'atomic_radius', 'melting_point', 'boiling_point',
        'density', 'atomic_volume', 'fusion_heat', 'evaporation_heat', 'thermal_conductivity', 'specific_heat']

# Filter the periodic table data based on the intersection of element names
intersection = set(elements["Name"]).intersection(ptable["symbol"])
mask = ptable["symbol"].isin(intersection)
ptable_filtered = ptable[mask]

# Create a dataframe with selected columns
ptable_filtered = pd.DataFrame(ptable_filtered, columns=cols)

# Rename the "symbol" column to "Name"
ptable_filtered = ptable_filtered.rename(columns={"symbol": "Name"})

In [11]:
ptable_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 83 entries, 0 to 93
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    83 non-null     object
 1   atomic_number           83 non-null     int64
 2   atomic_weight           83 non-null     float64
 3   group_id                64 non-null     float64
 4   period                  83 non-null     int64
 5   electron_affinity       68 non-null     float64
 6   en_pauling              79 non-null     float64
 7   en_allen                63 non-null     float64
 8   vdw_radius              83 non-null     float64
 9   covalent_radius_pyykko  83 non-null     float64
 10  atomic_radius           83 non-null     float64
 11  melting_point           0 non-null      float64
 12  boiling_point           0 non-null      float64
 13  density                 83 non-null     float64
 14  atomic_volume           81 non-null     float64
 15  fusion_heat             70 non-null     float64
 16  evaporation_heat        78 non-null     float64
 17  thermal_conductivity    61 non-null     float64
 18  specific_heat           0 non-null      float64
dtypes: float64(16), int64(2), object(1)
memory usage: 13.0+ KB

In [12]:
ptable_filtered.to_csv('mendeleve_elements.csv')